#!/usr/bin/env python
import subprocess

print('starting')
subproc_http = subprocess.Popen('python httpserver', stdout=subprocess.PIPE, universal_newlines=True, shell=True)
print('after first')
subproc_ftp = subprocess.Popen('python ftpserver', stdout=subprocess.PIPE, universal_newlines=True, shell=True)
print('after second')

while(True):
    data_http = subproc_http.stdout.read(1)
    data_ftp = subproc_ftp.stdout.read(1)
    print('FTP***{}'.format(data_ftp))
    print('HTTP***{}'.format(data_http))