#!/usr/bin/env python
import subprocess

print('starting')
subproc_http = subprocess.Popen('python httpserver', stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True, shell=True)
print('after first')
subproc_ftp = subprocess.Popen('python ftpserver', stderr=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True, shell=True)
print('after second')

while(True):
    data_http = subproc_http.stdout.read(76)
    data_ftp = subproc_ftp.stdout.read(76)
    print('running')
    print('FTP***{}'.format(data_ftp))
    print('HTTP***{}'.format(data_http))