// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard/DashPacket.proto

package org.team5499.robots.frc2018.dashboard;

public final class DashPacketProtos {
  private DashPacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DashPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dashboard.DashPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float battVoltage = 1;</code>
     */
    boolean hasBattVoltage();
    /**
     * <code>optional float battVoltage = 1;</code>
     */
    float getBattVoltage();
  }
  /**
   * Protobuf type {@code dashboard.DashPacket}
   */
  public  static final class DashPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dashboard.DashPacket)
      DashPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DashPacket.newBuilder() to construct.
    private DashPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DashPacket() {
      battVoltage_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DashPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              battVoltage_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.Builder.class);
    }

    private int bitField0_;
    public static final int BATTVOLTAGE_FIELD_NUMBER = 1;
    private float battVoltage_;
    /**
     * <code>optional float battVoltage = 1;</code>
     */
    public boolean hasBattVoltage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional float battVoltage = 1;</code>
     */
    public float getBattVoltage() {
      return battVoltage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, battVoltage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, battVoltage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket)) {
        return super.equals(obj);
      }
      org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket other = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) obj;

      boolean result = true;
      result = result && (hasBattVoltage() == other.hasBattVoltage());
      if (hasBattVoltage()) {
        result = result && (
            java.lang.Float.floatToIntBits(getBattVoltage())
            == java.lang.Float.floatToIntBits(
                other.getBattVoltage()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBattVoltage()) {
        hash = (37 * hash) + BATTVOLTAGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getBattVoltage());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dashboard.DashPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dashboard.DashPacket)
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.Builder.class);
      }

      // Construct using org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        battVoltage_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstanceForType() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.getDefaultInstance();
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket build() {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket buildPartial() {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket result = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.battVoltage_ = battVoltage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) {
          return mergeFrom((org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket other) {
        if (other == org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.getDefaultInstance()) return this;
        if (other.hasBattVoltage()) {
          setBattVoltage(other.getBattVoltage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float battVoltage_ ;
      /**
       * <code>optional float battVoltage = 1;</code>
       */
      public boolean hasBattVoltage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional float battVoltage = 1;</code>
       */
      public float getBattVoltage() {
        return battVoltage_;
      }
      /**
       * <code>optional float battVoltage = 1;</code>
       */
      public Builder setBattVoltage(float value) {
        bitField0_ |= 0x00000001;
        battVoltage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float battVoltage = 1;</code>
       */
      public Builder clearBattVoltage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        battVoltage_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dashboard.DashPacket)
    }

    // @@protoc_insertion_point(class_scope:dashboard.DashPacket)
    private static final org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket();
    }

    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DashPacket>
        PARSER = new com.google.protobuf.AbstractParser<DashPacket>() {
      public DashPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DashPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DashPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DashPacket> getParserForType() {
      return PARSER;
    }

    public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dashboard_DashPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dashboard_DashPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032dashboard/DashPacket.proto\022\tdashboard\"" +
      "!\n\nDashPacket\022\023\n\013battVoltage\030\001 \001(\002B9\n%or" +
      "g.team5499.robots.frc2018.dashboardB\020Das" +
      "hPacketProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dashboard_DashPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dashboard_DashPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dashboard_DashPacket_descriptor,
        new java.lang.String[] { "BattVoltage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
