// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/org/team5499/robots/frc2018/dashboard/DashPacket.proto

package org.team5499.robots.frc2018.dashboard;

public final class DashPacketProtos {
  private DashPacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DashPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dashboard.DashPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> 
        getParametersList();
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getParameters(int index);
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    int getParametersCount();
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    java.util.List<? extends org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder> 
        getParametersOrBuilderList();
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder getParametersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code dashboard.DashPacket}
   */
  public  static final class DashPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dashboard.DashPacket)
      DashPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DashPacket.newBuilder() to construct.
    private DashPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DashPacket() {
      parameters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DashPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                parameters_ = new java.util.ArrayList<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param>();
                mutable_bitField0_ |= 0x00000001;
              }
              parameters_.add(
                  input.readMessage(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.Builder.class);
    }

    public interface paramOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dashboard.DashPacket.param)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>optional string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>optional string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code dashboard.DashPacket.param}
     */
    public  static final class param extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dashboard.DashPacket.param)
        paramOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use param.newBuilder() to construct.
      private param(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private param() {
        key_ = "";
        value_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private param(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_param_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_param_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder.class);
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private volatile java.lang.Object value_;
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param)) {
          return super.equals(obj);
        }
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param other = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param) obj;

        boolean result = true;
        result = result && (hasKey() == other.hasKey());
        if (hasKey()) {
          result = result && getKey()
              .equals(other.getKey());
        }
        result = result && (hasValue() == other.hasValue());
        if (hasValue()) {
          result = result && getValue()
              .equals(other.getValue());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasKey()) {
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
        }
        if (hasValue()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dashboard.DashPacket.param}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dashboard.DashPacket.param)
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_param_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_param_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder.class);
        }

        // Construct using org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_param_descriptor;
        }

        public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getDefaultInstanceForType() {
          return org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.getDefaultInstance();
        }

        public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param build() {
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param buildPartial() {
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param result = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param) {
            return mergeFrom((org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param other) {
          if (other == org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>optional string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>optional string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dashboard.DashPacket.param)
      }

      // @@protoc_insertion_point(class_scope:dashboard.DashPacket.param)
      private static final org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param();
      }

      public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<param>
          PARSER = new com.google.protobuf.AbstractParser<param>() {
        public param parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new param(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<param> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<param> getParserForType() {
        return PARSER;
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PARAMETERS_FIELD_NUMBER = 1;
    private java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> parameters_;
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    public java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    public java.util.List<? extends org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder> 
        getParametersOrBuilderList() {
      return parameters_;
    }
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
     */
    public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder getParametersOrBuilder(
        int index) {
      return parameters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeMessage(1, parameters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < parameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, parameters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket)) {
        return super.equals(obj);
      }
      org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket other = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) obj;

      boolean result = true;
      result = result && getParametersList()
          .equals(other.getParametersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dashboard.DashPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dashboard.DashPacket)
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.class, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.Builder.class);
      }

      // Construct using org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParametersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          parametersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.internal_static_dashboard_DashPacket_descriptor;
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstanceForType() {
        return org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.getDefaultInstance();
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket build() {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket buildPartial() {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket result = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket(this);
        int from_bitField0_ = bitField0_;
        if (parametersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            parameters_ = java.util.Collections.unmodifiableList(parameters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.parameters_ = parameters_;
        } else {
          result.parameters_ = parametersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) {
          return mergeFrom((org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket other) {
        if (other == org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.getDefaultInstance()) return this;
        if (parametersBuilder_ == null) {
          if (!other.parameters_.isEmpty()) {
            if (parameters_.isEmpty()) {
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParametersIsMutable();
              parameters_.addAll(other.parameters_);
            }
            onChanged();
          }
        } else {
          if (!other.parameters_.isEmpty()) {
            if (parametersBuilder_.isEmpty()) {
              parametersBuilder_.dispose();
              parametersBuilder_ = null;
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              parametersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParametersFieldBuilder() : null;
            } else {
              parametersBuilder_.addAllMessages(other.parameters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> parameters_ =
        java.util.Collections.emptyList();
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          parameters_ = new java.util.ArrayList<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param>(parameters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder> parametersBuilder_;

      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> getParametersList() {
        if (parametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parameters_);
        } else {
          return parametersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public int getParametersCount() {
        if (parametersBuilder_ == null) {
          return parameters_.size();
        } else {
          return parametersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param getParameters(int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);
        } else {
          return parametersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder setParameters(
          int index, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.set(index, value);
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder setParameters(
          int index, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder addParameters(org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder addParameters(
          int index, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(index, value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder addParameters(
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder addParameters(
          int index, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder addAllParameters(
          java.lang.Iterable<? extends org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param> values) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, parameters_);
          onChanged();
        } else {
          parametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder clearParameters() {
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          parametersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public Builder removeParameters(int index) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.remove(index);
          onChanged();
        } else {
          parametersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder getParametersBuilder(
          int index) {
        return getParametersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder getParametersOrBuilder(
          int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);  } else {
          return parametersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public java.util.List<? extends org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder> 
           getParametersOrBuilderList() {
        if (parametersBuilder_ != null) {
          return parametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parameters_);
        }
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder addParametersBuilder() {
        return getParametersFieldBuilder().addBuilder(
            org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.getDefaultInstance());
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder addParametersBuilder(
          int index) {
        return getParametersFieldBuilder().addBuilder(
            index, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.getDefaultInstance());
      }
      /**
       * <code>repeated .dashboard.DashPacket.param parameters = 1;</code>
       */
      public java.util.List<org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder> 
           getParametersBuilderList() {
        return getParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder> 
          getParametersFieldBuilder() {
        if (parametersBuilder_ == null) {
          parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.param.Builder, org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket.paramOrBuilder>(
                  parameters_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          parameters_ = null;
        }
        return parametersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dashboard.DashPacket)
    }

    // @@protoc_insertion_point(class_scope:dashboard.DashPacket)
    private static final org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket();
    }

    public static org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DashPacket>
        PARSER = new com.google.protobuf.AbstractParser<DashPacket>() {
      public DashPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DashPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DashPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DashPacket> getParserForType() {
      return PARSER;
    }

    public org.team5499.robots.frc2018.dashboard.DashPacketProtos.DashPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dashboard_DashPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dashboard_DashPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dashboard_DashPacket_param_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dashboard_DashPacket_param_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:src/org/team5499/robots/frc2018/dashbo" +
      "ard/DashPacket.proto\022\tdashboard\"b\n\nDashP" +
      "acket\022/\n\nparameters\030\001 \003(\0132\033.dashboard.Da" +
      "shPacket.param\032#\n\005param\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\tB9\n%org.team5499.robots.frc20" +
      "18.dashboardB\020DashPacketProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dashboard_DashPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dashboard_DashPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dashboard_DashPacket_descriptor,
        new java.lang.String[] { "Parameters", });
    internal_static_dashboard_DashPacket_param_descriptor =
      internal_static_dashboard_DashPacket_descriptor.getNestedTypes().get(0);
    internal_static_dashboard_DashPacket_param_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dashboard_DashPacket_param_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
